# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: f486bcc7a785d1c727d6fc2b3bbf4aa9279a3b09cb20de08338788910332c2c0c8eca45abfbe3473f5134321978e095d1afc54b902c16a625e2b3cfbf22d8795

test:
  domain_name: example.com 
  secret_key_base: 76e68972f9875375f1288c7db7b44554ead1648c32f25d721e676473659bb34db84ced1e9fc6110b14b468eda2d68679265b00e360a71ef8c5b80ac7dd8a82b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

#PUBLISHABLE_KEY=pk_test_E1vH7bBsPR4CbQ869JrUVjQj SECRET_KEY=sk_test_8H10V5ENrIilUzbRXga8fzbh rails s
